- web/src/App.tsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/lib/games.ts
https://app.asana.com/0/1161945053441353/1178760399401475/f
> Add game grid and game sorting

- web/src/components/Games.jsx
Clicking the action menu on a game should trigger the game details, iff you're on the sidebar view.
> [web] select game when edit action clicked

- mobile/src/Teacher/index.js
- mobile/src/Teacher/screens/Explore/DetailScreen.js
- mobile/src/Teacher/screens/Explore/NavBarView/index.js
- mobile/src/Teacher/screens/Explore/QuestionCard.js
- mobile/src/Teacher/screens/Explore/index.js
This PR consists of implementing the further details page (DetailScreen) for the teacher side of the mobile app. Currently, you can navigate to the details of each game on a separate screen and show/hide hints of each question and navigate back to the ExploreScreen. There are still a few tasks I would need to finish to complete the further details Page. 
1) The hints for each question are mostly centered but could be done better with the hint number better aligned
2) The show/hide button needs a design square next to them.
3) The "<" on the DetailScreen Header to navigate back was implemented through Text. I plan to import a vector icon instead.
4) The DetailScreen has the existing bottom tab navigator from the ExploreScreen. I plan to remove that by nesting the needed tab navigators …
> create Further Details Page teacher side

- backend/schema.graphql
- web/.graphqlconfig.yml
- web/src/API.ts
- web/src/App.tsx
- web/src/components/Status.tsx
- web/src/components/StatusPageContainer.tsx
- web/src/graphql/mutations.ts
- web/src/graphql/schema.json
- web/src/graphql/subscriptions.ts
Proof of concept for Teacher Projection app. Try starting the app, and going to http://localhost:3000/status/1234. Should be blank.
Then open the console and run this query:
```graphql
mutation updateExistingGameToTriggerSubscription {
updateGameStatus(gameID: 1234, screenData: {screenID: QuestionScreen, text: "What's 2+2?", title: "Question 1", answers: ["4"]}) {
__typename
gameID
screenID
text
title
... on QuestionScreen {
answers
}
}
}
```
https://console.aws.amazon.com/appsync/home?region=us-east-1#/mz6btgo62nhu5dcl67k5namuwe/v1/queries
You can switch the pages by sending `screenID` JoinScreen, QuestionScreen, or ScorecardScreen.
> [StatusPage] proof of concept for GraphQL subscription

- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- web/src/components/SortByDropdown.jsx
- web/src/lib/sorting.ts
- Add sort by dropdown menu onto game dashboard
- Style dropdown to appear like Figma (font family, font sizing, menu option position, etc. still need tweaking)
- Add all menu options from Figma (some options are hidden from view due to not having their filtering added yet)
- Add Oldest filtering and Z to A filtering
- Fix issue with Alphabetical and Z to A filtering treating uppercase and lowercase letters differently. Both filters should now work accurately _most_ of the time.
- Last Updated and Oldest filters still need to be fixed. Once the API is corrected both filters should work correctly automatically.
- Fix some React errors in other files
> Add Sort By Dropdown and Fix Filtering

- web/src/host/pages/GameInProgress.jsx
- web/src/mocks/gamesession.json
I used AWS Amplify to generate teams, teammembers and team answers and then queried the gamesession. I updated our mock data with the result of that query (just copy and pasted the teams data I received). I've then done a series of nested .maps to scan through all the isChosen variables and count them, before passing that onto the footer component. I did the counting in the Game In Progress page but let me know if that isn't accurate.
> Footer API Calls - Number of Answers in Progress Bar

- debug-panel/public/index.html
- debug-panel/src/App.tsx
- networking/src/ApiClient.ts
- networking/src/IGameSession.ts
With new Amplify gql generated models, there's a new capability of filtering the data and only subscribe to the data changes you're interested in. For the start, adding the capability to only listen to a specific game session changes by using its ID. `debug-panel` is also updated to use this new capability
> [networking] Add filtering capability to subscriptions

- networking/src/ApiClient.ts
- networking/src/Models/IGameSession.ts
- web/src/host/components/CurrentStudents.jsx
- web/src/host/components/FooterGameInProgress.jsx
- web/src/host/components/FooterStartGame.jsx
- web/src/host/components/QuestionCard.jsx
- web/src/host/components/QuestionCardDetails.jsx
- web/src/host/containers/GameSessionContainer.tsx
- web/src/host/pages/GameInProgress.jsx
- web/src/host/pages/Ranking.jsx
Had issues with the current question index displaying properly in the header of the `GameInProgress` page. The length of how many questions in the questions array was also being miscalculated - by reading a length of 1 extra question object. 
Add an `if` statement in the `GameInProgress` page to set the `currentQuestionId` to `1` if it is `null`
This does seem to fix the issue of `.length` properly calculating the amount of question objects that are in the array, and also seems to fix the index marker and header in the UI.
> Lucah endicott  host question index

- debug-panel/src/App.tsx
- networking/amplify/backend/api/mobile/schema.graphql
- networking/amplify/team-provider-info.json
- networking/schema.graphql
- networking/src/AWSMobileApi.ts
- networking/src/ApiClient.ts
- networking/src/ModelHelper.ts
- networking/src/Models/IQuestion.ts
- networking/src/graphql/schema.json
- networking/src/graphql/subscriptions.ts
- Add subscriptions to get team updates based on a game session id. This needs to be tested
- Randomize creating an answer to a question in debug panel
- Minor formatting
- Parse choices and instructions for both lambda and graphql responses as one sends down an array and the other sends down a stringified json
- Change the default game id for debug panel as the previous one has been deleted
> Fix parsing choices and instructions for question

- mobile/src/Student/components/Card/index.js
- mobile/src/Student/components/RoundTextIcon/index.js
- mobile/src/Student/screens/Game/Components/HintsView/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/containers/GameSessionContainer.js
> Currently the wrong answer explanations are separated in individual cards with proper titles, but need to get them separated to be "swipable" left and right. Each one needs to fill the the screen individually
> 
> Seems like a Carousel indexing issue perhaps?
> 
> [Phase 2 Source code](https://github.com/rightoneducation/righton-app/tree/dev/mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay)
> [Component rendering the carousel Component](https://github.com/rightoneducation/righton-app/tree/dev/mobile/src/Student/components/HorizontalPageView)
https://github.com/rightoneducation/righton-app/issues/383
> [Mobile][Phase 2] cards working correctly based on current state

- host/src/components/GameAnswers.jsx
- host/src/components/GameAnswersDropdown.jsx
`host` resolution to https://github.com/rightoneducation/righton-app/issues/423
Looks like:
I'll merge but let me know if you are looking for anything else here @amarax
> Adding linebreaks to Wrong Answer Explanation on Host

- mobile/src/Student/screens/PhaseResult/index.js
- networking/src/ApiClient.ts
This is in response to: https://github.com/rightoneducation/righton-app/issues/434
Issue: scores not currently showing on leaderboard on `host`
Cause: `mobile` doesn't update backend with scores
Resolution: `apiClient.updateTeam` added to `PhaseResults` so that backend is updated between rounds with correct scores.
> [Mobile] Scores not updating backend

- play/src/pages/GameInProgress.tsx
This PR sets up the basic UI framework for GameInProgress. 
It follows the Responsive Guidelines in Figma here: 
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12367-382145
The logic of the layout is drawn out below:
> [Play] - GameInProgress UI Framework

- play/src/components/joingame/SelectAvatar.tsx
- play/src/containers/GameSessionContainer.tsx
- play/src/pages/JoinGame.tsx
This PR is in response to Mani's comment on PR590 [here](https://github.com/rightoneducation/righton-app/pull/590#discussion_r1178384738).
**Issue:**
On default load, the current behaviour shows a default monster selected but a null value for the white border. This means there's a splicing of the values at default with `selectedAvatar` having a default of null and the `<Monster>` tag assigning a value of `0` in this condition (all in `SelectAvatar.tsx`).
U/X has requested that the default value for the team selection be randomly generated and a white border shown around the icon by default. To achieve this, `selectedAvatar` defaults to a random number
> [Play] - Random default values for Select Avatar page

- play/src/components/AnswerCard.tsx
- play/src/components/ButtonSubmitAnswer.tsx
- play/src/components/finalresults/Congrats.tsx
- play/src/components/gameinprogress/ChooseAnswer.tsx
- play/src/containers/GameInProgressContainer.tsx
- play/src/containers/GameSessionContainer.tsx
- play/src/pages/FinalResults.tsx
- play/src/pages/GameInProgress.tsx
**Update:**
There are a few PRs outstanding that are nested in the below structure (with PR608 as the base):
[[Play] - Join_Game Functionality Flow #608](https://github.com/rightoneducation/righton-app/pull/608)
-> [[Play] - GameInProgress and Final Results Functionality Flow #613](https://github.com/rightoneducation/righton-app/pull/613)
->-> [[Play] - Internationalisation via react-i18next for JoinGame Flow #610](https://github.com/rightoneducation/righton-app/pull/610)
->->-> [[Play] - Internationalisation for GameInProgress and FinalResults #611](https://github.com/rightoneducation/righton-app/pull/611)
**Description:**
This PR extends from [[Play] - Join_Game Functionality Flow #608](https://github.com/rightoneducation/righton-app/pull/608) and adds functionality for routing and team …
> [Play] - GameInProgress and Final Results Functionality Flow

- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
**Issue:**
3-2-1 timer is showing on the start of every question, rather than just when the player enters the game.
Hoisting `isModalOpen` to the `GameSessionContainer` allows for the resetting of the state and the passing of the updated value down to the correct switch. It needs to be at this level in the tree because this is where it is initially set by `handleStartGame`.
Relevant code:
- `isModalOpen` in `GameSessionContainer` - `state` value that controls visibility of 3-2-1 timer modal
**Preview:**
https://github.com/rightoneducation/righton-app/assets/79417944/aee477b1-a483-4df4-a804-abff6b7dac58
> [Host] - Prevent 3-2-1 timer showing on every question

- play/src/pages/GameInProgress.tsx
**Issue:**
Per [Issue 625](https://github.com/rightoneducation/righton-app/issues/625), some questions aren't displaying on the `play` app. This is due to the way that we're breaking down the inputted question text (that comes into the backend as a single string) to provide the bold text face on `play` that is specified in the Figma. For example:
Inputted text would be all in one block so we are breaking this string down to be able to bold just the question.
The question text breakdown as been resolved to handle the following types of input: 
1. Single line with/without question marks:
> Examples:
> Simplify the expression y=(2x+3) ^2 + (4x+3)^2
> The tallest skyscraper in the world is located in which country?
>
> Result: entire line bolded
2. Multiline question with …
> [Play] - Rework of Question Text Processing

- play/public/locales/en/translation.json
- play/public/locales/es/translation.json
- play/src/components/DiscussAnswerCard.tsx
- play/src/lib/Theme.tsx
**Issue:**
Per this [Issue](https://github.com/rightoneducation/righton-app/issues/620), it was decided to provide large, more prominent text for the 'Nice Try'/'Correct!' text on Discuss Answer.
The styling of the text has been adjusted.
Relevant code:
- `DiscussAnswerCard.tsx` - styling for text
**Preview:**
https://github.com/rightoneducation/righton-app/assets/79417944/83934576-19d7-4ef8-a33e-0da4accf3cf0
> [Play] - Nice try/Correct Text on Discuss Answers

- play/src/lib/Theme.tsx
- play/src/pages/pregame/SplashScreen.tsx
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/629). U/X has the following comments: 
1. Increase spacing between Join Game button and bottom of screen
The spacing has been increased per Figma (64 px) 
Relevant code:
- `extraExtraLargePadding` in `Theme.lib` - additional padding value added to theme with 64px value
**Preview:**
> [Play] - Revisions from U/X Comments (Splash Screen)

- play/src/containers/PregameContainer.tsx
- play/src/pages/pregame/EnterGameCode.tsx
- play/src/pages/pregame/EnterPlayerName.tsx
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/631). U/X has the following comments: 
1. Change the font in the input fields to Poppins
2. Adjust the spacing  on mobile devices.
Font has been changed to Poppins. Spacing of elements on Enter Player Name and Enter Game Code, when mobile device is used, has been increased from 4 to 5.
Relevant code:
- ` <StackContainer spacing={isSmallDevice ? 4 : 5}>` in `EnterPlayerName.tsx` - additional padding value added to theme with 64px value
**Preview:**
> [Play] - Revisions from U/X Comments (Player Name)

- play/src/components/AnswerCard.tsx
- play/src/components/DiscussAnswerCard.tsx
- play/src/components/QuestionCard.tsx
- play/src/components/ResultsCard.tsx
- play/src/lib/styledcomponents/BodyCardStyled.tsx
- play/src/lib/styledcomponents/layout/ScrollBoxStyled.tsx
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/639). U/X has the following comments: 
1. Adjust the softness of the drop shadow on the cards.
The cards box shadow have been adjusted to match the Figma. This has been done throughout the app. 
Relevant code:
- ` boxShadow:  '0px 8px 16px -4px rgba(92, 118, 145, 0.4)'` in `BodyCardStyled.tsx`
**Preview:**
> [Play] - Revisions from U/X Comments (Discuss Answers)

- play/public/locales/en/translation.json
- play/public/locales/es/translation.json
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/638). U/X has the following comments: 
1. Adjust text from "trick answer" to "incorrect answer"
2. Adjust text from "Swipe to the left to answer the question" to "Swipe left to answer the question"
Text value in translation dictionaries updated.
Relevant code:
- `incorrectText2` in `translation.json` 
- `swipealert` in `translation.json`
**Preview:**
> [Play] - Revisions from U/X Comments (Phase 2 Choose Answer)

- play/src/pages/finalresults/Congrats.tsx
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/640). U/X has the following comments: 
1. Increase padding from top of screen to title text
Padding value added
Relevant code:
- `paddingTop: `${theme.sizing.largePadding}px`,` to `Congrats.tsx`
**Preview:**
> [Play] - Revisions from U/X Comments (FinalResults)

- play/public/manifest.json
**Issue:**
Currently, when our app is added to the home screen on iPhones, the title is displayed as Right On!:
This should be changed to RightOn!
`manifest.json` has been updated to `RightOn!`.
Relevant code:
- `play/public/manifest.json` 
**Preview:**
> [Play] - update PWA title per U/X comments

- play/src/pages/pregame/SelectAvatar.tsx
**Issue:**
This PR revises comments from this [Issue](https://github.com/rightoneducation/righton-app/issues/632). U/X has the following comments: 
1. Adjust spacing between avatars (size verified to match Figma)
2. Adjust padding from bottom of screen to button.
`spacing` changed to `gridGap` on `GridContainer`. `paddingBottom` added based on `isSmallDevice`
Relevant code:
-  `gridGap: ${theme.sizing. extraSmallPadding}px` in `SlectedAvatar.tsx`
- `paddingBottom: isSmallDevice ? ${theme.sizing.extraExtraLargePadding}px: ${theme.sizing.largePadding}px,` in `SelectedAvatar.tsx` 
**Preview:**
> [Play] - Revisions from U/X Comments (Select Avatar)

- play/src/lib/Theme.tsx
- play/src/pages/pregame/EnterGameCode.tsx
- play/src/pages/pregame/EnterPlayerName.tsx
- play/src/pages/pregame/SplashScreen.tsx
**Issue:**
The input text field on the Enter Game Code screen needs to be wider. 
The main stack container that hosts the entire screens width has been set with a `minWidth` property that aligns to the width per Figma:
Relevant code:
- `Theme.tsx` - `const pregameMinColumnWidth = 215; `
**Preview:**
Original:
Revised:
> [Play] - Revisions from U/X Comments (Enter Game Code)

- play/src/i18n.tsx
**Issue:**
The design team noticed that a 404 error was thrown when a user's browser settings didn't contain one of the languages `play` supports. 
`i18next` provides a `SupportedLngs` configuration option (https://www.i18next.com/overview/configuration-options). If a user's language is detected outside of this range, it will automatically fallback to the default without throwing the 404. 
Relevant code:
- `i18n.tsx` - `.init({
fallbackLng: 'en',
supportedLngs: ['en', 'es']`...
> [Play] - i18next error, 404 translation.json not found before hitting fallback

- play/package.json
**Issue:**
Prettier/Eslint configuration was happening in `.prettierrc` and `.eslintrc`, respectively, which is then ignored by .gitignore. To share these settings across developers, these settings have been moved to `package.json`
Settings moved to `package.json`. Please ensure that you delete any local eslint and prettier dotfiles from your `play` folders. Eslint's precedence hierarchy puts `package.json` files under local files, so those local files need to be deleted for our `package.json` settings to apply. Prettier reverses this order so it should be fine, but for cleanliness we might as well remove them. 
For example delete the `.esclintrc.json` and `.prettierrc` files struck out in the below snip:
Relevant code:
- `eslintConfig` in `package.json` - linting config …
> [Play] - Moving Eslint/Prettier configuration settings to package.json

- play/src/containers/GameInProgressContainer.tsx
**Issue:**
In `GameInProgressContainer.tsx` ln 34 produces a null runtime error if the player navigates to play.rightoneducation.com/game, without joining a game first. The code is `const { currentTimer } = localModel;`
This is due to the fact that we're trying to destructure localModel.currentTimer when localModel is null. If we move `localModel.currentTimer` down to the render function on ln 81, this error is avoided because that function will only render when `localModel` is populated. Then, the `isNullOrUndefined` check on ln 45 won't be interrupted and the player will be routed back to `/` automatically. 
Relevant code:
- `GameInProgressContainer.tsx` - ln81 - move `localModel.currentTimer` to a location where `localModel` !== null
> [Play] - currentTimer null value produces error

- play/src/App.tsx
- play/src/components/RejoinModal.tsx
- play/src/containers/GameInProgressContainer.tsx
- play/src/containers/PregameContainer.stories.tsx
- play/src/containers/PregameContainer.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/lib/PlayModels.tsx
- play/src/pages/pregame/SplashScreen.tsx
**Issue:**
The Design team noted that we should prevent the rejoin behaviour if a certain time period has elapsed. This is so we can avoid a situation such as a student crashing out of a game and then, on the next day, using the `play` app again and being asked if they want to join the day old game. 
@amarax, I've set the 'expiration' time to 2 hrs, pretty arbitrarily. Let me know if you think there's a better interval for this. 
While there isn't an explict means of expiring `localStorage` data, the conventional way to do this is to store the time at which the localStorage data is stored and then compare that to the expiry interval when loading. We are doing that on both the `PregameContainer` and `GameInProgressContainer`, specifically within the `fetchLocalData` …
> [Play] - Prevent rejoin functionality from triggering after a set time period

- play/src/containers/GameInProgressContainer.tsx
**Issue:**
Catching an issue with the loader from [PR666](https://github.com/rightoneducation/righton-app/pull/666) that resulted from a merge conflict.
PR666 was using an outdated way of redirecting. This has been adjusted. 
**Relvant Code:**
-`LocalModelLoader` function in `GameInProgressContainer.tsx`
> [Play] - Loader fix from PR#666

- play/src/components/GameSessionSwitch.tsx
- play/src/components/HeaderContent.tsx
- play/src/components/Timer.tsx
- play/src/pages/GameInProgress.tsx
**Issue:**
We were originally importing the localModel at the `Timer` component level. This means that every time the timer rerendered (continuously), we would call `fetchLocalData` and it would retrieve from local data. We need to prevent this from happening.
We've passed down the `localModel` all the way from `GameSessionSwitch` to the `Timer` component as a prop. This means that the value won't change when the `Timer` rerenders. So that `fetchLocalData` function only runs on the loaders.
Relevant code:
- `const rejoinGameObject = fetchLocalData()` - removed from `Timer.tsx`
- `localModel={localModel}` - added to `GameInProgress.tsx` and subcomponents through to `Timer.tsx`
> [Play] - Localstorage Timer fix

- play/public/locales/en/translation.json
- play/public/locales/es/translation.json
- play/src/components/ErrorModal.tsx
- play/src/containers/PregameContainer.tsx
- play/src/lib/PlayModels.tsx
- play/src/pages/pregame/SelectAvatar.tsx
**Issue:**
This PR addresses git issue #671: 
No UI error handling for API errors on choose avatar screen
As was suggested, the solution was to incorporate the ErrorModal component into the SelectAvatar component by passing in relevant information from PregameContainer to SelectAvatar and expand ErrorModal's functionality to respond to errors when players fail to join the game.
Relevant code:
_Adding ErrorModal for Pregame_:
In `PregameContainer.tsx`:
-Pass `APIError` into `<SelectAvatar>` on `line 164` to determine if error modal should be displayed
In `SelectAvatar.tsx`:
-`<ErrorModal>` component added on `lines 116-121`, taking in `displayErrorModal` (passed in from parent as `APIError`) as an argument for `isModalOpen` on `line 117`
In `PlayModels.tsx`:
-Added element …
> [Play] - Error handling on SelectAvatar click of Pregame Flow

- play/src/components/Timer.tsx
**Issue:**
I missed this issue in https://github.com/rightoneducation/righton-app/pull/677. If we are passing the `localModel` that was loaded from the loader and then updating it continuously from the `Timer.tsx` it will always have `hasRejoined: false` on this screen. 
We need to updated `hasRejoined: true` when we are also updating with the `currentTimer` value, so that if a user reloads the page, they are routed through the correct rejoin logic. We can set `hasRejoined: true` here unilaterally because we only ever `fetchLocalData` in the loader functions on the pages. Therefore, we know that once they hit this timer function, any time we are updating `localModel` it will be in the `hasRejoined: true` condition.
Relevant code:
- `hasRejoined: true` in `Timer.tsx`
> [Play] - timer fix - hasRejoined Condition

- play/src/pages/finalresults/Leaderboard.tsx
**Issue:**
Solves the issue of the team avatar values being regenerated and randomized every time the screen is resized. Github: https://github.com/rightoneducation/righton-app/issues/652
Previous PR: https://github.com/rightoneducation/righton-app/pull/656
I had to create a new branch due to merge errors.
Originally the team avatars were being set at a random value which would regenerate each time the component was re-rendering, including when the screen would be resized. I took it outside of the component function and used a useRef hook so that it is randomized only once and then stored and returned. It is only regenerated when the teams or teamId also changes.
To deal with the runtime errors when the player is not in last place, I made a few adjustments. The function …
> [Play] - Randomization of team avatars on leaderboard

- play/src/pages/finalresults/Leaderboard.tsx
Github Issue: https://github.com/rightoneducation/righton-app/issues/673
In the event of a tie, players are not displayed alphabetically.
Location in [Design Comments Document](https://docs.google.com/document/d/1EyyDVn2hgrPhgxTok5Qf0AFVjNPh0PVeWxjKCWQtx2c/edit): issue # 2 (on the bottom of Page 10).
The teamSorter function has been modified to detect a tie in the rankings and sort that subset of players alphabetically.
Leaderboard.tsx
**Preview:**
The leaderboard without the alphabetically ordered tied teams ^^
Here is the updated leaderboard ^^
> [Play] - Leaderboard - Tied Teams Sorting #673

- networking/src/ApiClient.ts
- networking/src/Models/IAWSGameSession.ts
- networking/src/Models/ITeam.ts
- play/src/mock/MockGameSession.json
**Issue:**
Following, https://github.com/rightoneducation/righton-app/pull/686, this updates models and mocked data to include `selectedAvatarIndex`
Adds `selectedAvatarIndex` field to models.
> [Play] - Adding selectedAvatarIndex to models

- play/src/pages/finalresults/Leaderboard.tsx
**Issue:**
Issue:
Issue on github item: "From https://github.com/rightoneducation/righton-app/pull/695. In my review, I missed that we're still using the original sortedTeams logic as well as the new Set-based sorting. I'm pretty sure we can delete the original sortedTeams logic and just convert the set but it'd be good to verify this."
Github item: https://github.com/rightoneducation/righton-app/issues/696
Proposed resolution on github item: "This task is to verify that we can remove the original sorting logic (ln 39-53) on Leaderboard.tsx. If possible, delete that code and just use teams."
I've changed the array that the set takes from sortedTeams to just teams. In my review of the code, I'm not sure how it would be possible to get rid of the original sorting logic (In …
> [Play] - Verify if we can remove the initial team sort on Leaderboard.tsx #696

- play/.gitignore
- play/.storybook/main.js
- play/.storybook/preview-head.html
- play/.storybook/preview.js
**Issue:**
Storybook configuration files are stored by default in a `.storybook` folder. Our `.gitignore` contains `.*` effectively ignoring the config files, meaning that multiple devs may have different configs. 
An exception has been added to `.gitignore` so that the folder is no longer ignored and we have a single source of truth for storybook config files.
Relevant code:
- `!/.storybook/` - in `.gitignore`
> [Play] - Remove .storybook config folder from .gitignore

- host/src/mock/MockGameSession.json
- networking/src/ApiClient.ts
- networking/src/Models/ITeamAnswer.ts
- play/src/mock/MockGameSession.json
**Issue:**
This PR updates the `networking` layer to reflect the changes in https://github.com/rightoneducation/righton-app/pull/751, namely the addition of the `confidenceLevel` field to `teamAnswers` as well as `ConfidenceLevel` enum to `ITeamAnswer`
> [Networking] - ConfidenceLevel Parameter

- host/src/components/ConfidenceResponses/ConfidenceResponseGraph.jsx
- host/src/components/Responses/ResponsesGraph.jsx
**Issue:**
By default, Victory charts process scroll events for subcomponents, as described [here](https://github.com/FormidableLabs/victory/issues/2565). This prevents scroll events from working when the user touchs the Victory graph on mobile. 
Per the thread above, we can add a custom container component styled with `touchActions: auto` to override this default behaviour and reenable scrolling when touching Victory charts. 
Relevant code:
On all `<VictoryChart>` components:
```
<VictoryChart
... 
containerComponent={ // <--- add this
<VictoryContainer 
style={{
touchAction: "auto"
}}
/>
}
...
>
```
> [Host] - Enable scroll on mobile for Victory Charts

- host/src/components/EnableConfidenceCard.jsx
**Issue:**
It was determined that the existing styling of the switch on in `host` that enables the Confidence features was confusing. Instead of using a blue color to denote an enabled state, it was decided that enabled would have a white toggle switch with a darker track and disabled would be a greyed out version of that. Please see the videos below for a preview.
Existing:
https://github.com/rightoneducation/righton-app/assets/79417944/008efc06-a118-4791-a0f8-382acec038fc
Restyled:
https://github.com/rightoneducation/righton-app/assets/79417944/db468e67-37bd-4078-89f7-2b5e38cf4ec8
> [Host] - Restyles Confidence Switch

- networking/amplify/backend/api/mobile/schema.graphql
- networking/amplify/team-provider-info.json
- networking/src/ApiClient.ts
- networking/src/Models/IQuestion.ts
- networking/src/graphql/mutations.ts
- networking/src/graphql/queries.ts
- networking/src/graphql/subscriptions.ts
**Issue:**
In the interest of accepting Short Answer Responses, we will need to store the short answer response information alongside the `choices` in which we are currently storing the multiple choice information. This information will be stored on an individual answer basis in the `TeamAnswer` object but it will be useful to also store it here during both gameplay and for analytics on a question basis after the fact. This object is currently a string but will be updated with more type-specificity in a following PR
```
type Question @model(subscriptions: null, timestamps: null) {
id: Int! @primaryKey(sortKeyFields: ["order", "gameSessionId"])
text: String!
choices: AWSJSON
responses: AWSJSON // <------ new 
imageUrl: String
instructions: AWSJSON
standard: String
cluster: …
```
> [Networking] - Adds Responses field to Question Object

- central/src/components/CreateQuestion.jsx
- central/src/components/CreateQuestionAnswerDropdown.jsx
- central/yarn.lock
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/containers/GameSessionContainer.tsx
- host/yarn.lock
This PR adds two updates:
1. Mirrors the same validation logic used on `play` for when a teacher creates a question in `central`. If a teacher were to enter an invalid number, it would cause havoc in the game so we need to ensure that they are following the format they specify with the radio buttons. 
2. Fixes a bug with the confidence levels on `host` that arose from a mismatch of naming.
> [Central/Host] - Verify teacher input when creating questions and host bug

- host/src/containers/GameSessionContainer.tsx
- host/src/lib/HelperFunctions.jsx
- networking/src/ApiClient.ts
- networking/src/Models/AnswerClasses.ts
- play/public/locales/en/translation.json
- play/src/components/openanswercard/OpenAnswerCard.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/lib/styledcomponents/ShortAnswerTextFieldStyled.tsx
- play/src/pages/GameInProgress.tsx
This PR includes one update:
1. If we allow the teacher to specify the answer type up front, we don't have a huge need for the Quill pad, as we can just convert any math expressions directly into Latex ourselves. As such, we no longer need to deal with the handling of the Quill delta object and we can probably get a better user experience using mui TextFields to keep things consistent.
> [Play] - Swaps out Quill.JS pad for mui TextField

- host/src/components/FooterGame.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/LinearProgressBar.jsx
- host/src/components/PlayerThinking/PlayerThinking.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
This is the first of a few PRs for the Hint feature that will use GPT-4 to categorize hints. The PRs breakdown as follows:
[[Host] - Enable/disable Hint Feature on Host #896](https://github.com/rightoneducation/righton-app/pull/896)
-> [[Play/Networking] - Intakes hints on play, updates networking to send them to backend #897](https://github.com/rightoneducation/righton-app/pull/897)
->->[[Host/Play/Networking] - Updates across the apps to handle intaking/sending to lambda hints by host #898](https://github.com/rightoneducation/righton-app/pull/898)
->->->[[Host/Play] - Bug Fixes #899](https://github.com/rightoneducation/righton-app/pull/899)
->->->->[[Host/Networking] - Prompt Adjustment #900](https://github.com/rightoneducation/righton-app/pull/900)
->->->->->[[Host/Networking] - Moves …
> [Host/Networking] - Moves the processing of hints to next phase

- host/src/components/FooterGame.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/LinearProgressBar.jsx
- host/src/components/PlayerThinking/PlayerThinking.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
- host/src/pages/StudentViews.jsx
- networking/src/ApiClient.ts
- networking/src/Models/IQuestion.ts
- play/public/locales/en/translation.json
- play/public/locales/es/translation.json
- play/src/components/ButtonSubmitAnswer.tsx
- play/src/containers/GameInProgressContainer.tsx
- play/src/containers/PregameContainer.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/lib/PlayModels.tsx
- play/src/pages/GameInProgress.tsx
This is the first of a few PRs for the Hint feature that will use GPT-4 to categorize hints. The PRs breakdown as follows:
[[Host] - Enable/disable Hint Feature on Host #896](https://github.com/rightoneducation/righton-app/pull/896)
-> [[Play/Networking] - Intakes hints on play, updates networking to send them to backend #897](https://github.com/rightoneducation/righton-app/pull/897)
->->[[Host/Play/Networking] - Updates across the apps to handle intaking/sending to lambda hints by host #898](https://github.com/rightoneducation/righton-app/pull/898)
->->->[[Host/Play] - Bug Fixes #899](https://github.com/rightoneducation/righton-app/pull/899)
->->->->[[Host/Networking] - Prompt Adjustment #900](https://github.com/rightoneducation/righton-app/pull/900)
->->->->->[[Host/Networking] - Moves …
> [Host/Play] - Bug Fixes

- host/src/components/FooterGame.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/LinearProgressBar.jsx
- host/src/components/PlayerThinking/CustomBar.jsx
- host/src/components/PlayerThinking/CustomLabel.jsx
- host/src/components/PlayerThinking/PlayerThinking.jsx
- host/src/components/PlayerThinking/PlayerThinkingGraph.jsx
- host/src/components/PlayerThinking/PlayerThinkingGraph.stories.jsx
- host/src/components/PlayerThinking/PlayerThinkingSelectedAnswer.jsx
- host/src/components/PlayerThinking/PlayersSelectedAnswer.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
- host/src/pages/StudentViews.jsx
- networking/src/ApiClient.ts
- networking/src/IApiClient.ts
- networking/src/Models/IQuestion.ts
- play/public/locales/en/translation.json
- play/public/locales/es/translation.json
- play/src/components/ButtonSubmitAnswer.tsx
- play/src/containers/GameInProgressContainer.tsx
- play/src/containers/PregameContainer.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/lib/PlayModels.tsx
- play/src/pages/GameInProgress.tsx
This is the first of a few PRs for the Hint feature that will use GPT-4 to categorize hints. The PRs breakdown as follows:
[[Host] - Enable/disable Hint Feature on Host #896](https://github.com/rightoneducation/righton-app/pull/896)
-> [[Play/Networking] - Intakes hints on play, updates networking to send them to backend #897](https://github.com/rightoneducation/righton-app/pull/897)
->->[[Host/Play/Networking] - Updates across the apps to handle intaking/sending to lambda hints by host #898](https://github.com/rightoneducation/righton-app/pull/898)
->->->[[Host/Play] - Bug Fixes #899](https://github.com/rightoneducation/righton-app/pull/899)
->->->->[[Host/Networking] - Prompt Adjustment #900](https://github.com/rightoneducation/righton-app/pull/900)
->->->->->[[Host/Networking] - Moves …
> [Host/Play/Networking] - Updates across the apps to handle intaking/sending to lambda hints by `host`

- host/src/components/GameInProgressContentSwitch.jsx
- host/src/pages/GameInProgress.jsx
**Issue:**
Currently, we are scrolling to the top of the screen when a component is clicked: https://github.com/rightoneducation/righton-app/issues/906 
Changed ref to point to subcomponent containing text that says "Showing players who answered:"
Relevant code:
- In `host` > `src` > `components` > `GameInProgressContentSwitch.jsx` > lines `57-82`: removed ref assignment from parent div and added new div wrapper with ref assignment to component we want to scroll to on `lines 70, 71`: 
`<div id="responses-scrollbox"
ref={responsesRef}>
<SelectedAnswer...`
**Preview:**
In the below video, we can see the scroll behavior on bar click has changed so that we focus on the subcomponent containing text that says "Showing players who answered:" …
> [Host] - Scroll screen on graph click

- play/src/components/HintCard.tsx
- play/src/components/OpenAnswerCard.tsx
Textfields were not being disabled when a student submitted their answer, causing confusion. This update disables the fields on submit via 
```
disabled={isSubmitted}
```
or 
```
disabled={isHintSubmitted}
```
> [Play] - Disable text field on short answer or hint submit

- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/PlayerThinking/PlayerThinkingSelectedAnswer.jsx
- host/src/components/PlayerThinking/PlayersSelectedAnswer.jsx
- host/src/containers/GameSessionContainer.tsx
- networking/src/Models/IQuestion.ts
Fixes these two issues:
- [[Q1 Dev PM] - [LHF] - Hint all team names start with "Team" #940](https://github.com/rightoneducation/righton-app/issues/940)
- [[Q1 Dev PM] - [LHF] - Show Student Hints on Host #936](https://github.com/rightoneducation/righton-app/issues/936)
Updated behaviour can be seen in the video below:
https://github.com/rightoneducation/righton-app/assets/79417944/0c698e6a-6608-454e-8fd7-e9ec2302812f
> [Host] - Display player hints on when clicking on hints graph

- central/src/components/GameDashboard.jsx
- host/src/components/FeaturedMistakes.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/LinearProgressBar.jsx
- networking/amplify/team-provider-info.json
- networking/src/Models/AnswerClasses.ts
- play/src/components/GameSessionSwitch.tsx
- play/src/containers/PregameContainer.tsx
https://docs.google.com/document/d/1qrd4EKozYLYnbKpVRjA-ysuClvETTKHWXHWgOJXKubQ/edit
Resolved Bugs:
- P1 - Host: Short Answer Mode: Manual selection for Phase 2 does not work
Issue: `answerChoices` does not update correctly with `isSelectedMistake`
Resolution: Adjusted logic for when to parse `isSelectedMistake` from `Question` object
- P2 - Host: Short Answer Mode: “Use the top 3 answers by popularity” sometimes results in more than 3 distractors being displayed in Play in Phase 2
Issue: Answers with differing decimal places are being seen as equal, thus pushing more distractors over to phase 2
Resolution: Adjusted normalization and comparison logic for numeric answers to check for differing decimal places and reject answers that don't have the same number
- P2 - Short Answer Mode - …
> [Central/Host/Play] - Bug Fixes

- central/package.json
- central/yarn.lock
- networking/package.json
- networking/src/@types/aws/aws-exports.d.ts
- networking/src/APIClients/index.ts
- networking/src/APIClients/interfaces/index.ts
- networking/yarn.lock
- play/src/pages/gameinprogress/ChooseAnswer.tsx
**Issue:**
The issue was that when the confidence meter was not enabled, users were still able to swipe to where the confidence meter would have been. This solution makes it so that they are not able to swipe in that scenario.
> [play] fixing ghost swipe bug when confidence meter is not enabled

- central/src/components/GameMaker.jsx
Resolves 'P4.1 Change “Game Text” to “Game Description” across Central pages' in https://docs.google.com/document/d/1AmQZHwj8mV1IMNGsgssL57NcIpNwxTeYsQgFFe_3aKY/edit
> [Central] - Change 'Game Text' to 'Game Description'

- central_v2/src/hooks/useExploreGamesStateManager.tsx
- central_v2/src/pages/ExploreGames.tsx
- central_v2/src/switches/AppSwitch.tsx
- networking/src/APIClients/datamanagers/CentralDataManagerAPIClient.ts
- networking/src/APIClients/datamanagers/interfaces/ICentralDataManagerAPIClient.ts
Hi @maniramezan, here's another PR that finishes the foundational work required for `central_v2`. This extracts the state management into a custom hook so we can init and handle state without mudding up our components. I've elected to not use context/reducers to handle some of this because (unlike host) I don't think we really have the deeply nested, single data object that causes a ton of prop drilling. 
So there are two main parts of the data structure:
1. Custom hooks - these will be for state management and each major part of the app will have its own. They contain the necessary functions required to handle state.
2. CentralDataManager - this is the class that handles all the API calls that the state managers will need. We have this in context so we can make use of it across our …
> [Central_v2] - Game TEmplate State Manager

- central_v2/src/components/profile/OwnerCard.tsx
- central_v2/src/lib/styledcomponents/OwnerCardStyledComponents.tsx
- central_v2/src/pages/UserProfile.tsx
- networking/src/APIClients/auth/AuthAPIClient.ts
- networking/src/APIClients/auth/interfaces/IAuthAPIClient.ts
- networking/src/APIClients/datamanagers/CentralDataManagerAPIClient.ts
- networking/src/APIClients/datamanagers/interfaces/ICentralDataManagerAPIClient.ts
- networking/src/Models/AWS/AWSUser.ts
- networking/src/Parsers/UserParser.ts
**Issue:**
Task:
- User should be able to edit their information:
-  ChangeAvatar
-  Username
-  FirstName,
-  LastName,
-  FrontImage
-  BackImage
-  Password
Users have given the ability to change their avatar, firstname, lastname, frontimage, and backimage. Giving users the ability to change password has not been implemented yet. Need more information from the design team on figma. 
Relevant code:
- UserProfile.tsx: This component captures the whole page. This is where the UserInterface is laid out for that page.
- UserProfileImageUploadModal.tsx: The component is responsible for letting user upload their image or choose an avatar.
- AuthAPIClient.tsx: A file that lives in networking responsible for connecting with the backend. This is also where we added the function …
> functionlity for userProfile page finished.

- central_v2/src/components/question/ViewQuestionCards.tsx
Resolves: https://github.com/rightoneducation/righton-app/issues/1660
- remove overflow from card container
- make entire page scrollable (similar to create game and create question).
> [Central_v2] - Bug Resolution - M8
