- package.json
- web/fake question.txt
- web/public/index.html
- web/public/manifest.json
- web/src/App.jsx
- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- web/src/components/QuestionForm.jsx
- web/src/data/Games.json
> add question form

- web/src/components/QuestionForm.jsx
> add delete solution step button

- web/src/components/GameForm.jsx
> move add question button

- web/package.json
- web/src/App.tsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/NewGameDialogue.jsx
- web/src/components/QuestionForm.jsx
- web/src/lib/games.ts
- web/src/types.ts
> [API] add create and save game requests

- web/src/App.tsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/QuestionForm.jsx
This fixes this bug:
> Issue Tracker
> https://bit.ly/2WR6g26
> 
> When I go into a game and try to edit a question or add a question, it's not saving to the game.  Actually it does save, but it won't appear unless I reload the page
> 
> Steps to Reproduce
> 1. Edit "Jordan Game Test2"
> 2. Edit "Q1 of new Game"
> 3. Change Answer1 to something else like answer2
> 4. Save
> Nothing Happens, save is not recording
> [API] handle various loading/refetch state errors

- web/public/index.html
- web/src/API.ts
- web/src/components/Games.jsx
- web/src/graphql/mutations.ts
- web/src/graphql/queries.ts
- web/src/graphql/schema.json
- web/src/graphql/subscriptions.ts
- web/src/lib/games.ts
- web/src/types.ts
> sort games by updated at and open the newest on create

- web/package.json
- web/public/index.html
- web/src/API.ts
- web/src/components/EditGameDialogue.jsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/QuestionForm.jsx
- web/src/graphql/mutations.ts
- web/src/graphql/queries.ts
- web/src/graphql/schema.json
- web/src/graphql/subscriptions.ts
- web/src/lib/games.ts
- web/src/types.ts
Edit game via dialogue rather than the game form.
> [UI] move title and description to game edit form

- web/src/App.tsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- web/src/components/QuestionForm.jsx
Major changes to Game page, Question cards, and save behavior.
> UI changes for Games page and Question cards

- web/src/components/CCSSField.jsx
- web/src/components/EditGameDialogue.jsx
- web/src/components/Games.jsx
- web/src/components/NewGameDialogue.jsx
https://app.asana.com/0/1161945053441353/1164978560354737/f
> Add CCSS field

- web/src/components/Games.jsx
- web/src/lib/games.ts
> Game card UI changes

- web/src/App.tsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- web/src/lib/games.ts
- Issue #5 #15 #16  Game Card Changes
- Add CCSS field to the Game form
- Navbar should say "RightOn Game Builder"
> Add game actions (delete / duplicate)

- web/src/App.tsx
- web/src/components/Games.jsx
Grab the index of the newly added game (varies based on sorting) and select that game.
> select new game after duplication

- web/src/App.tsx
- web/src/components/AlertBar.jsx
- web/src/context/AlertContext.ts
Adding auto dismissing (after 6 seconds) alerts for new, edit, delete, and duplicate actions.
> [Alerts] Add alert bar and context

- web/src/App.tsx
Looks like this file is not used in the web and caused troubles to setup our amazing interns to onboard and run the web app : )
> Remove unnecessary AWS config and Amplify references

- mobile/App.js
- mobile/ios/Podfile.lock
1) Remove the references to AWS config file causing errors during runtime
2) Update `Podfile.lock` to be compatible with latest version of XCode
> Fix aws config issue on mobile

- mobile/ios/Podfile.lock
- mobile/package.json
Update RNReanimated Package causing errors on the initial screen for android phones
> Bug: Fix android bug on initialize screen

- backend/functions.json
- backend/mutations.json
- backend/queries.json
Back up resolvers on AWS in source control while working on them
> Back up latest resolvers

- web/src/App.tsx
- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- Moved search bar to Nav.jsx
- Removed search bar from Games.jsx
- Added CSS styling to search bar to match Figma
- Hid search filtering dropdown (for time being)
> Update search bar CSS and move to Nav bar

- web/src/App.tsx
- web/src/components/CCSS.tsx
- web/src/components/GameDashboard.jsx
- web/src/components/Games.jsx
- web/src/lib/questions.ts
- Created frontend code for ListQuestions API (for future use in Questions Dashboard and other areas)
- Updated Game Dashboard cards to current Figma design (Note: The overlapping CCSS text is not an issue, it is data that is currently in old Games created when testing the Resolvers)
> Updated Game Dashboard to Figma Design

- web/src/App.tsx
- web/src/components/Games.jsx
- web/src/components/Nav.jsx
- Add temporary search filter dropdown
- Games now update when selecting a new filter
- Closes #152
> Add search filter functionality

- web/src/components/Games.jsx
- web/src/components/SortByDropdown.jsx
- web/src/lib/sorting.ts
- Add Question Count dropdown
- Add Grade Level dropdown (currently has no functionality)
- Remove Alphabetical dropdown (filters still left in code if needed for future use)
- Add Ascending and Descending Question Count filters
- Add font from Figma to Sort By dropdown
> Add Question Count Filter and Update CSS

- web/src/components/Games.jsx
- Add Sort By dropdown back into `Games.jsx`
> Hotfixed Sort By Dropdown

- web/src/components/Nav.jsx
- web/src/components/SearchBar.jsx
Addressing Issue #183: "Hide Search Bar"
Update to ensure search bar is hidden when not on Explore page.
> Search Bar Update

- web/src/App.tsx
- web/src/components/AnswerDropdown.jsx
- web/src/components/GameDashboard.jsx
- web/src/components/GameForm.jsx
- web/src/components/GameMaker.jsx
- web/src/components/Nav.jsx
- web/src/components/QuestionDetail.jsx
- web/src/graphql/queries.ts
- web/src/lib/games.ts
- web/src/lib/questions.ts
- Created Game Maker UI (not functional) from scratch
#159 
#171 
- Added wrong answer functionality for the Question Detail screen & Added individual dropdown functionality for answers in the Question Detail screen
#155 
#180 
#181 
- Added alt tags to some image tags, as well as cleaning up some other code
> Create Game Maker UI

- web/src/components/CCSSField.jsx
- web/src/components/Nav.jsx
- web/src/components/QuestionDetail.jsx
- web/src/components/QuestionForm.jsx
- Wrong Answer Dropdowns now display wrong answers correctly
- Questions with no wrong answers can now be displayed in the question details screen (displays 'Wrong Answer Choice 1/2/3' and sets the explanation to 'N/A')
- Updated select dropdowns to stop causing Material UI errors in the console
- Other minor fixes to solve console errors
> Fix Wrong Answer Dropdowns

- backend/mutations.json
- web/src/API.ts
- web/src/GraphQLAPI.ts
- web/src/graphql/schema.json
Updating updateGame resolver to first remove all relationships in games_questions table and then add the ones passed into the game
> Update Game resolver to update game_questions relationship

- web/src/components/AddQuestion.jsx
- web/src/components/EditGameDialogue.jsx
- web/src/components/GameDashboard.jsx
- web/src/components/GameForm.jsx
- web/src/components/Games.jsx
- web/src/components/QuestionDetail.jsx
- web/src/components/QuestionForm.jsx
- web/src/lib/games.ts
@ryanabooth hi. can u lookie here?
> Lucah  change index

- backend/mobile-backend/schema.graphql
- backend/schema.graphql
Created a schema for the AppSync api which will be utilized by the mobile application
> Mobile backend generated from Amplify's CLI

- web/src/components/AnswerDropdown.jsx
- web/src/components/CCSS.tsx
- web/src/components/CreateQuestion.jsx
- web/src/components/GameMaker.jsx
- web/src/components/GameMakerCCSS.jsx
- web/src/components/Games.jsx
- web/src/components/SortByDropdown.jsx
Fixes for:
Issue #218 
Issue #217  
Issue #221
> Fix game ccss

- web/src/components/GameMaker.jsx
> Keep button disabled until any changes

- web/src/App.tsx
- web/src/components/GameLaunch.jsx
- web/src/components/Games.jsx
> Triple Dots for Game on Game Launch page

- web/host/AnswerDropdown.jsx
- Made answer dropdown component for RightOn Host
- Not linked to `GameInProgress.jsx` currently
- No dropdown functionality (arrow moves when hovered over)
- Number of students in game is currently static (stored as `numberOfStudents`)
- Answer text and number of students that picked the answers are currently passed down as props
- Bars in each dropdown accurately reflect the number of students that picked them out of `numberOfStudents`
- Dimensions based on Figma and might be too large / small
> Create Answer Dropdown Component for RightOn Host

- web/src/host/components/AnswersInProgress.jsx
- web/src/host/components/AnswersInProgressDetails.jsx
The following merge request includes the initial UI for the real-time answers when teachers view the game in progress. 
The dynamic data is yet to be implemented.
> Implement live game answers ui

- web/src/host/components/FooterStartGame.jsx
- web/src/host/components/GameCode.jsx
- web/src/host/components/HostHeader.jsx
- web/src/host/pages/StartGame.jsx
Still getting a handle on frequency of pull requests. This feels like a commit?
Anyway, further progress on StartGame.jsx/props/storybook:
1. fixed the footer position 
2. add gameCode prop. I don't think there's any remaining hardcoded variables for this page.
> StartGame.jsx - Setting up props for all the components

- debug-panel/README.md
Added the steps for getting the debug panel to run locally. Please adjust or edit as you see fit!
> initiating README.md with running debug panel locally steps

- web/src/App.tsx
- web/src/host/containers/GameInProgressContainer.jsx
- web/src/host/pages/GameInProgress.jsx
Initialized the `GameInProgressContainer` to load a game session by id. More work to be done in the `GameInProgress` page to actually utilize the information coming in from the mock data/ API.
> initialize game in progress container

- web/src/App.tsx
- web/src/host/components/CurrentStudents.jsx
- web/src/host/components/FooterStartGame.jsx
- web/src/host/pages/GameInProgress.jsx
- web/src/host/pages/StartGame.jsx
- web/src/lib/hostAPI.ts
Start Game Button from `StartGame` page is now routing to the `GameInProgress` page (phase 1 of 2).
Currently just using useHistory to hit the route. Need to add functionality for updating the current "game status" when clicked.
Cleaned up `GameInProgress` file by removing former divs and passing in our most recent components created for this page.
> Start Game button Route to Game In Progress page

- debug-panel/package.json
- debug-panel/src/App.tsx
- networking/amplify/.config/local-aws-info.json
- networking/amplify/backend/api/mobile/schema.graphql
- networking/amplify/backend/types/amplify-dependent-resources-ref.d.ts
- networking/package.json
- networking/schema.graphql
- networking/src/AWSMobileApi.ts
- networking/src/ApiClient.ts
- networking/src/IGameSession.ts
- networking/src/graphql/mutations.ts
- networking/src/graphql/queries.ts
- networking/src/graphql/schema.json
- networking/src/graphql/subscriptions.ts
https://github.com/rightoneducation/righton-app/issues/281
https://github.com/rightoneducation/righton-app/issues/282
> [networking] [debug-panel] Update states and add timer attribute

- debug-panel/src/App.tsx
- web/src/host/components/CurrentStudents.jsx
- web/src/host/components/FooterStartGame.jsx
- web/src/host/containers/GameSessionContainer.tsx
- web/src/host/pages/GameInProgress.jsx
- web/src/host/pages/StartGame.jsx
Added a function to game session container to update currentState of the game session. This can be passed as a prop to any page/ component that needs it.
> Lucah endicott  host session state handler

- web/src/host/components/AnswersInProgress.jsx
- web/src/host/components/AnswersInProgressDetails.jsx
- web/src/host/pages/GameInProgress.jsx
- web/src/host/pages/GameInProgress.stories.jsx
Next steps are to implement non-click on the correct answer and work with integrating the timer header on phase 2
> created base for phase 2 games storybook

- networking/src/ApiClient.ts
- networking/src/Models/IGameSession.ts
- web/src/host/components/CurrentStudents.jsx
- web/src/host/components/FooterGameInProgress.jsx
- web/src/host/components/FooterStartGame.jsx
- web/src/host/components/QuestionCard.jsx
- web/src/host/components/QuestionCardDetails.jsx
- web/src/host/containers/GameSessionContainer.tsx
- web/src/host/pages/GameInProgress.jsx
- web/src/host/pages/Ranking.jsx
- Add `title` field to IGameSession so we can access the title of a game for the start game page.
- Update mapping in host components to clear console errors.
- Remove console logs.
> lucah endicott  - update mapping in host components

- web/src/host/components/HeaderGameInProgress.jsx
- web/src/host/components/Timer.jsx
- web/src/host/components/Timer.stories.jsx
some ideas for edits @lucahendicott
can't get the storybook to build 😢
> recommended edits

- networking/src/ApiClient.ts
- networking/src/Models/IQuestion.ts
This aligns with backend changes to properly send back the json file and aligns with the new changes in the lambda to properly parse and insert `instructions` into game session
> Parse `instructions` and `choices` for game session

- central/src/components/GameLaunch.jsx
- host/src/App.tsx
- host/src/containers/CreateNewGameSession.tsx
Create the launch game button behaviour. Basically links to the host app, creates a new game session from the game id, and redirects to the new game session.
cc @lucahendicott @drewjhart
> [Central][Host] launch game working

- central/src/components/AddQuestion.jsx
- central/src/components/CreateQuestion.jsx
- central/src/components/QuestionDetail.jsx
Getting a lot of backend errors about characters, all in the choices array I think.
> [central] question form with answers back

- mobile/ios/Podfile.lock
- mobile/package.json
- mobile/src/Auth/screens/SignIn.js
- mobile/src/Navigator/index.js
- mobile/src/Student/screens/Game/BasicGamePlay/AnswerOptions/index.js
- mobile/src/Student/screens/Game/BasicGamePlay/index.js
- mobile/src/Student/screens/Game/GamePreview/index.js
- mobile/src/Student/screens/PregameCountDown/index.js
- mobile/src/Student/screens/StudentFirst/index.js
- mobile/src/Student/screens/StudentGameIntro/index.js
- mobile/src/Student/screens/StudentName/index.js
- mobile/src/containers/GameSessionContainer.js
- mobile/src/screens/OnboardAppRouter/index.js
Create game session container to load initial game state and pass to screens as props
- Store current game session to local storage
- load a game session from local storage if a game session in storage exists and set the game session data in the container to values from local storage
Update `OnboardAppRouter` to navigate to proper screens based on the `currentState` of the game session
> Lucah endicott  mobile initial state

- mobile/App.js
- mobile/src/Navigator/index.js
- mobile/src/Student/screens/PhaseResult/index.js
- mobile/src/Student/screens/ScorePage/index.js
- mobile/src/components/RoundButton/index.js
- networking/src/ApiClient.ts
- networking/src/IApiClient.ts
- Phase result is a placeholder so we can start hooking up all screens
- Added a method for calculating the wrong answer score. This is not tested, needs to be tested
- Add leadership button
> Add scoring and phase result

- mobile/src/Student/screens/PhaseResult/Answer/index.js
- mobile/src/Student/screens/PhaseResult/index.js
- networking/src/ModelHelper.ts
This still needs to be tested with e2e to confirm it works with the passed data in from the flow
PS: Ignore `Phase 1` in the header as that's read from the wrong variable during testing.
> Add phase two result

- mobile/ios/Podfile.lock
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/screens/JoinGame/index.js
Map wrong answer reasons to individual cards.
TODO: update carousel to swipe through each card
> map wrong answer reasons to individual cards.

- mobile/package.json
- mobile/src/Student/screens/Game/Components/Question/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/Student/screens/StudentName/index.js
Question cards now loading images
> fix question component to load question image url

- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/Student/screens/PregameCountDown/index.js
- mobile/src/screens/JoinGame/index.js
Render team footer component in phase 1 & phase 2
> Mobile: import team footer to phase 1 & 2 screens.

- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
Access team object in phase 1 & phase 2
> Mobil: filter teams by id in phase 1 & 2

- mobile/src/Navigator/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/Student/screens/PregameCountDown/index.js
- mobile/src/Student/screens/ScorePage/index.js
- mobile/src/containers/GameSessionContainer.js
- mobile/src/screens/JoinGame/index.js
Set team object in game session container to pass entire team object to other components as props
> Mobile: update team props

- mobile/src/Student/screens/PhaseResult/index.js
- networking/src/ModelHelper.ts
These changes haven't been tested
> Improvements to phase results

- host/src/containers/CreateNewGameSession.tsx
Based on feedback from Integration Testing #4, mobile is starting in TEAMS_JOINING. This code adjusts `CreateNewGameSession` to update the game session to TEAMS_JOINING so the apps begin in synch
> Host: starting state is TEAMS_JOINING

- mobile/src/Navigator/index.js
- mobile/src/Student/screens/Game/Leadership/Components/TeamItem/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/Student/screens/ScorePage/index.js
- networking/jest.config.ts
- Set isTrickAnswer to true in phase 2 answer submission. 
- Handle default for more than 5 players in leaderboard.
> Mobile: Update phase 2 answer submit API

- mobile/src/Student/screens/Game/Leadership/Components/TeamItem/index.js
- mobile/src/Student/screens/Game/Leadership/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/AnswerOptionsPhaseTwo/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- Update phase 2 ui - add submit answer button
- disable the correct answer option 
- disable answering after answer is submitted
- update `isTrickAnswer` to `true` when an answer is submitted
> Mobile: update phase 2 ui to reflect figma

- mobile/src/Student/screens/Game/Components/Question/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
> -  Update headers - spacing and size
> -   Add question image and question text to the card body (see updated figma screenshot below)
> -   Test a question with something in the instructions field to see if they parse out properly
> -   Handle UI for questions with no instructions in that field - maybe remove instructions card entirely if there aren't any?
https://github.com/rightoneducation/righton-app/issues/382
> [Mobile] Phase 1 discussion UI

- host/src/components/GameAnswers.jsx
- host/src/pages/GameInProgress.jsx
Add the correct answer explanation from the question.instructions field. Places "Step #" between each of the steps for clarity:
> Host: Correct answer explanation

- host/src/components/GameLoadModal.jsx
- host/src/components/LoadingIndicator.jsx
- host/src/containers/CreateNewGameSession.tsx
Update to the game create "rocket" screen. Still subject to change.
> Host: Create Game Screen

- mobile/android/app/build.gradle
- mobile/ios/Podfile.lock
- mobile/src/Student/components/HorizontalPageView/index.js
- mobile/src/Student/screens/Game/Components/HintsView/Hint/index.js
- mobile/src/Student/screens/Game/Components/HintsView/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/screens/JoinGame/index.js
- Update Android version
- Fix Codepush not downloading updates on Android
- Make sure node_modules and native codes for lib match the same version
> Several fixes

- mobile/src/Navigator/index.js
I stashed the Podfile.lock changes this time, had to pod update in ios in order for the xcode simulator to run.
> ios cannot swipe back now

- mobile/src/Student/screens/StudentName/index.js
Due to privacy concerns and the fact that this is not necessary, removing it now and replacing with a unique ID per game session
> Remove using device unique ID due to privacy

- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
> Josephina  mobile answer the question

- mobile/src/Student/screens/StudentName/index.js
- mobile/src/Student/screens/StudentName/styles.js
For some reason when I committed to the previous branch, a bunch of other files got changed so I just made a new branch but all of the comments from the previous pr have been addressed.
> Alex  mobile enter name app crash changes

- mobile/src/Student/screens/PhaseResult/Answer/index.js
- mobile/src/Student/screens/PhaseResult/index.js
Phase Results screen UI adjustments based on U/X team feedback. Changes involve adjusting  where the '%' is, as well as alignment of values on right side of screen. 
Existing:
New:
> Mobile - adjusting Phase Results Screen UI

- mobile/src/Student/components/Card/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
- mobile/src/Student/screens/PhaseResult/Answer/index.js
Adjusting card display on PhaseTwoBasicGamePlay and copying over Submit Answer button functonality from https://github.com/rightoneducation/righton-app/pull/514 to Phase Two
UI Update from:
This:
> Mobile - UI on PhaseTwoBasicGamePlay and Phase 2 Answer Button

- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
PR to address https://github.com/rightoneducation/righton-app/issues/523. Further comments/video capture has been added to the PR.
> [Mobile] - Disable button when no answer is selected or when answer has already been submitted

- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/AnswerOptionsPhaseTwo/index.js
- mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay/index.js
Minor adjustments but wanted to log them in a PR to trace how they follow out of https://github.com/rightoneducation/righton-app/pull/529 and https://github.com/rightoneducation/righton-app/pull/525
> [Mobile] - Phase 1 and Phase 2 Basic Gameplay Follow Up CSS adjustments 

- mobile/src/Student/screens/Game/Components/HintsView/Hint/index.js
- mobile/src/Student/screens/Game/PhaseOneBasicGamePlay/index.js
Stars will not be implemented this time around, but spacing and card size issues fixed
> Josephina  mobile item 485

- central/src/components/Nav.jsx
> [Central] - adding gamemaker button back in to Nav if user is authed

- central/src/components/GameForm.jsx
- central/src/components/GameLaunch.jsx
hamburger menus until we can rewrite the function
(current behaviour: deletes questions in game)
> temporarily removing "move up move down" buttons from central

- central/package.json
- central/src/components/OnboardingModal.jsx
Adding navigation arrows on onboarding modal per U/X team feedback
Note: new use of `react-responsive` to use `mediaQuery` to detect mobile device sizes. This is added to `package.json`
> [Central] Onboarding Modal - Navigation Arrows

- mobile/src/Student/containers/GameSessionContainer.js
- mobile/src/Student/screens/PhaseResult/index.js
Phase Results has been rewritten to remove redundant variables and to ensure that the calculation of scores is wrapped in `useFocusEffect` and `useCallback` so they are only run when the screen is shown.
> [Mobile] - Phase Result Clean Up

- play/src/components/HeaderContent.stories.tsx
- play/src/components/HeaderContent.tsx
- play/src/components/Timer.stories.tsx
- play/src/components/Timer.tsx
- play/src/mock/MockGameSession.json
- play/src/pages/GameInProgress.tsx
This update adds `HeaderContent` and `Timer` components/stories and adds these components to the `GameInProgress` screen. 
**`HeaderContent`**
Function: 
- Provides correct header text based on game state and student answer and shows Timer component if required.
Layout:
- Transparent background, expands to fill space provided by parent container
Props:
- `currentState` - to assign text and show timer
- `isPaused` - passed down to timer
- `isFinished` - passed down to timer
- `isCorrect` - to assign text
- `isIncorrect` - to assign text
- `handleTimerIsFinished` - callback function from Timer that is passed up and back from state management in `GameSessionContainer`
Stories:
https://64220218d457f84ba4546eb1-umgthooiff.chromatic.com/?path=/story/design-system-3-organisms-headercontent--choos …
> [Play] - HeaderContent and Timer Components

- play/src/components/Timer.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/pages/GameInProgress.tsx
- play/src/pages/gameinprogress/ChooseAnswer.tsx
**Issue:**
This PR addresses the 3 issues mentioned in git issue #667:
(1) The string that shows the time has an issue when seconds reach 0 (should be 3:00 -> 2:59 but instead is 2:00 -> 2:59)
(2) Timer expands and contracts slightly as the time changes
(3) When the timer reaches 0, the player is still able to submit answers
For issue:
(1) I noticed that the timer seemed to be functioning correctly when testing. My guess was that the addition of the useMemo() in the recent timer-refresh PR resolved this issue and after some testing on both the old and new version of Timer confirmed this was the case. Essentially what was happening earlier was that the currentTimeInput would be calculated as a float more frequently than each whole second. 
i.e. (in the case where totalTime …
> [Play] - Miscellaneous Timer Issues 

- play/src/components/FooterContent.tsx
- play/src/components/GameSessionSwitch.tsx
- play/src/components/ScoreIndicator.tsx
- play/src/pages/PhaseResults.tsx
**Issue:**
Per issue # 1 of the [Design team testing document ](https://docs.google.com/document/d/1EyyDVn2hgrPhgxTok5Qf0AFVjNPh0PVeWxjKCWQtx2c/edit), the score is currently not being updated if the tab is inactive when the teacher passes the Phase Results page. This means that if a student changes tabs and misses the Phase Result screen, they won't get their points.
The main issue here is that we're initialising `score` in `GameSessionSwitch` as `state`. Because of this, we only catch the changes to the `gameSession` prop on initialisation. Any future changes in the gameSession prop with respect to score, won't be caught.  
This initially seems like a place for a `useEffect` (as it will allow us to update the score both locally and from the prop). However, we only really …
> [Play] - Score is updated regardless of if tab is active or inactive

- debug-panel/package.json
- debug-panel/src/App.tsx
- host/package.json
- play/package.json
- play/src/hooks/useFetchAndSubscribeGameSession.tsx
**Issue:**
Issue is mainly the update game session failing after `selectedAvatarIndex` added
Still WIP
> Clean up build scripts

- play/public/locales/en/translation.json
- play/src/components/GameSessionSwitch.tsx
- play/src/containers/FinalResultsContainer.tsx
**Issue:**
This PR addresses git issue #672:
(1) The Top 5 banner is displayed regardless of if a player is in the top 5
(2) 'Top 5' should be capitalized on 'Top 5' banner of congratulations screen
(1) Provide additional logic handling to pass into `Congrats.tsx` to determine if 'Top 5' banner should be displayed or 'Great Job' banner
(2) Adjust text item for top 5 banner in `translation.json`
Relevant code:
For item 1:
-Brought down logic handling of determining if the player is in the top five from previous `const leader` in `GameSessionSwitch.tsx` to `FinalResultsContainer.tsx` by removing prop `leader` from `FinalResultsContainer` in `FinalResultsContainer.tsx` and defining the following within that file:
-created function `isLeader` on `lines 34-45` which takes in …
> [Play] -  Congratulations screen

- host/.storybook/main.js
- host/.storybook/preview.js
- host/package.json
- host/src/components/FooterGame.stories.jsx
- host/src/components/HeaderGame.stories.jsx
- host/src/components/Timer.stories.jsx
- host/src/mock/MockGameSession.json
- host/src/pages/GameInProgress.jsx
- host/src/pages/GameInProgress.stories.jsx
- host/src/pages/StartGame.stories.jsx
- host/yarn.lock
**Issue:**
Similar to https://github.com/rightoneducation/righton-app/pull/727, this PR migrates our version of Storybook to 7.0.27.
> [Host] - Migrates to Storybook ^7.0.27

- play/src/components/ScoreIndicator.tsx
**Issue:**
It was determined that the new score animation (when a player is awarded points) isn't noticable enough on the screen. 
The animation was adjusted to add a rotation and to increase the duration. 
Relevant code:
- `ScoreIndicator.tsx`:
```
'@keyframes newScoreUp': {
'0%': { transform: 'translateY(-110%) rotate(0deg) scale(1.0)' },
'10%': { opacity: 1, transform: 'translateY(-110%) rotate(0deg) scale(1.2)' },
'15%, 25%': { opacity: 1, transform: 'translateY(-110%) rotate(-12deg) scale(1.2)' },
'20%, 30%': { opacity: 1, transform: 'translateY(-110%) rotate(12deg) scale(1.2)' },
'40%': { opacity: 1, transform: 'translateY(-110%) rotate(0deg) scale(1.0)' },
'100%': { transform: 'translateY(0)' },
},
```
Updated 08/10/2023 per feedback with:
```
const …
```
> [Play] - New Score Animation

- networking/amplify/backend/api/mobile/schema.graphql
- networking/src/graphql/mutations.ts
- networking/src/graphql/queries.ts
- networking/src/graphql/subscriptions.ts
- play/src/mock/MockGameSession.json
**Issue:**
Continued changes to  accomodate for changes in the backend during the development of surfacing student thinking.
> [Networking] - Surfacing Thinking changes 2

- central/src/components/GameLaunch.jsx
- debug-panel/src/App.tsx
- host/src/App.tsx
- host/src/containers/CreateNewGameSession.tsx
- host/src/containers/GameSessionContainer.tsx
- mobile/global.js
- networking/src/ApiClient.ts
- play/src/App.tsx
- play/tests/unittests/mock/ApiClient.mock.ts
Current backend environments are as follows:
- `main` - production backend, uses builds from `main` github branch
- `dev` - developer backend, uses builds from `dev` github branch
- `test` - environment for breaking backend changes, uses builds from local development github branches
Initially, `dev` branch was targeting `test` backend, which I think is confusing so I'm going with the above.
> [Host/Play/Networking] - Updates Environment and URLS to target dev backend env

- host/src/components/Responses/CustomLabel.jsx
- host/src/lib/HelperFunctions.jsx
- networking/src/Models/ITeamAnswerContent.ts
- play/src/components/ButtonSubmitAnswer.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/pages/GameInProgress.tsx
**Issue:**
During a meeting, Sinclair and I generated the following document to track how we want the Short Answer Response feature to respond:  [RightOn PWA1.1 - Short Answer Responses - Answer Handling Coordination](https://docs.google.com/document/d/1Zu405H2wDkLOMgLUQQTFTikFDPl6wL_HE5y6_alxOBw/edit)
Coming out of that, we required the following changes:
1. We needed to be able to catch if students are entering multiple numeric answers to try and game the system. For example, if the correct answer is '1200', '1200, 1100, 1500' should not also be considered correct. 
2. We need to be able to ensure that strings would be caught regardless of other words in the string. For example, if the correct answer is 'Amygdala', 'the amygdala' should also be considered correct (we're already catching …
> [Host/Play/Networking] - Short Answer Response - Adjusts Answer Handling

- host/src/components/FeaturedMistakes.jsx
- host/src/components/Responses/CustomLabel.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/lib/HelperFunctions.jsx
- host/src/pages/GameInProgress.jsx
- networking/src/ApiClient.ts
- networking/src/Models/IQuestion.ts
- networking/src/Models/ITeamAnswerContent.ts
- play/src/components/ButtonSubmitAnswer.tsx
- play/src/components/GameSessionSwitch.tsx
- play/src/components/openanswercard/OpenAnswerCard.tsx
- play/src/lib/HelperFunctions.tsx
- play/src/pages/gameinprogress/ChooseAnswer.tsx
**Issue:**
This PR fixes some miscellaneous bugs based, for example if a student enter a plain number as an expression, how phase two answers are displayed after short answers in phase one, and preventing swiping when the quill pad is focused. 
_Note: this PR is a part of a multi-part PR for the Short Answer Responses feature. The full PR structure is below:
[[Play/Networking] - Short Answer Response Base #844](https://github.com/rightoneducation/righton-app/pull/844)
->[[Host] - Short Answer Response Base #845](https://github.com/rightoneducation/righton-app/pull/845)
->->[[Networking/Host] - Short Answer Response Updates to Backend #848](https://github.com/rightoneducation/righton-app/pull/848)
->->->[[Play] - Short Answer Response Scoring …
> [Play/Host] - Short Answer Response - Bug Fixes

- host/src/components/FooterGame.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/LinearProgressBar.jsx
- host/src/components/PlayerThinking/PlayerThinking.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
- networking/src/ApiClient.ts
This is the first of a few PRs for the Hint feature that will use GPT-4 to categorize hints. The PRs breakdown as follows:
[[Host] - Enable/disable Hint Feature on Host #896](https://github.com/rightoneducation/righton-app/pull/896)
-> [[Play/Networking] - Intakes hints on play, updates networking to send them to backend #897](https://github.com/rightoneducation/righton-app/pull/897)
->->[[Host/Play/Networking] - Updates across the apps to handle intaking/sending to lambda hints by host #898](https://github.com/rightoneducation/righton-app/pull/898)
->->->[[Host/Play] - Bug Fixes #899](https://github.com/rightoneducation/righton-app/pull/899)
->->->->[[Host/Networking] - Prompt Adjustment #900](https://github.com/rightoneducation/righton-app/pull/900)
->->->->->[[Host/Networking] - Moves …
> [Host/Networking] - Prompt Adjustment

- central/schema.graphql
- central/src/components/CreateQuestion.jsx
- central/src/components/CreateQuestionAnswerDropdown.jsx
- host/src/components/EnableShortAnswerCard.jsx
- host/src/components/FeaturedMistakes.jsx
- host/src/components/GameInProgressContentSwitch.jsx
- host/src/components/MistakeSelector.jsx
- host/src/components/MistakeSelector.stories.jsx
- host/src/components/Responses/ResponsesGraph.jsx
- host/src/containers/GameSessionContainer.tsx
- host/src/pages/GameInProgress.jsx
- networking/src/Models/AnswerClasses.ts
- networking/src/Models/ITeamMember.ts
- play/public/locales/en/translation.json
- play/tests/unittests/mock/MockHelperFunctions.ts
Based on the nested nature of PR 875 and co, I am creating this PR from `dev` and using it for comment resolution. I have linked the code in the comments.
> Comment Resolution for [Play/Networking] - Short Answer Response Base #875

- networking/src/Models/IQuestion.ts
- play/src/components/ConfidenceMeterCard.tsx
- play/src/components/OpenAnswerCard.tsx
- play/src/pages/GameInProgress.tsx
- play/src/pages/gameinprogress/ChooseAnswer.tsx
See Row 5 in this Teacher Feedback sheet for complete details on the problem:
https://docs.google.com/spreadsheets/d/1_3wO_OfDmoJagddHVPv6mBydOvF74wosvpImlLdnznA/edit#gid=0
See this slack thread for further details on the resolution:
https://righton-education.slack.com/archives/C02D6KZ029L/p1706008233774669
Preview:
https://github.com/rightoneducation/righton-app/assets/79417944/4b616d84-f589-48c2-ae41-b7598ddc5afb
> [LHF] - Scrolling Behaviour on Submit Answer

- central/src/components/GameLaunch.jsx
- central/src/components/GameMaker.jsx
- central/src/components/Games.jsx
- central/src/components/QuestionMaker.jsx
- central/src/containers/RouteContainer.tsx
> [Central] - Bug fixes

- central/src/components/GameMaker.jsx
- central/src/components/Games.jsx
- central/src/components/QuestionMaker.jsx
- central/src/containers/RouteContainer.tsx
- central/src/lib/API/GameTemplates.ts
- host/src/containers/GameSessionContainer.tsx
- host/src/lib/HelperFunctions.jsx
- networking/src/Models/AnswerClasses.ts
Associated bug fixes in the creation (central) and playing (host) of games
> [Central/Host] - Bug Fixes

- central/src/containers/RouteContainer.tsx
- host/src/containers/GameSessionContainer.tsx
Hints need to be parsed prior to sending to lambda function.
> [Host] - Fixes parsing issue with hints for grouphints Lambda Function

- host/babel.config.js
- host/package.json
- host/src/components/FeaturedMistakes.jsx
- host/src/lib/HelperFunctions.jsx
- host/src/tests/FeaturedMistakes.test.tsx
- host/tsconfig.json
- host/yarn.lock
- networking/amplify/team-provider-info.json
- networking/src/ModelHelper.ts
- play/src/components/AnswerCard.tsx
- play/src/components/ButtonSubmitAnswer.tsx
This PR fixes bugs per:
[2024-04-25 & 2024-05-08 GW Carver UX Session Bugs](https://docs.google.com/document/d/1qrd4EKozYLYnbKpVRjA-ysuClvETTKHWXHWgOJXKubQ/edit)
The following bugs are resolved:
1. P2.3: [Olivia] Play: Multiple Choice Mode: Students who answer correctly receive a “Nice try” message instead of “Correct!”
2. P2.4 [Olivia] Play: Multiple Choice Mode: Player should be able to press Submit only after a response has been entered
3. P3.3: [Olivia K] Host: Short Answer Response Mode: Default “top 3 answers by popularity” for Phase 2 are not ordered as expected. 
For 3, `jest` was added to more systematically test the sorting behaviour. You can find the test file at [FeaturedMistakes.test.jsx](https://github.com/rightoneducation/righton-app/pull/1083/files#diff-8ac0347e7b00102efdc2 …
> Carver Bugs - Second Round

- host/src/components/GameInProgressContentSwitch.jsx
- host/src/pages/GameInProgress.jsx
Fixes as a result of: https://github.com/rightoneducation/righton-app/pull/1118
> [Host/Play] - Minor fixes from merging #1118 into dev

- host_v2/public/locales/en/translation.json
- host_v2/public/locales/es/translation.json
- host_v2/src/components/EndGame/EndGameHeader.tsx
- host_v2/src/components/FooterStartGame.tsx
- host_v2/src/components/HeaderContent.tsx
- host_v2/src/components/HostHeader.tsx
- host_v2/src/components/LeaderboardHeader.tsx
- host_v2/src/components/PrepareGameContent/EnableConfidenceCard.tsx
- host_v2/src/components/PrepareGameContent/EnableShortAnswerCard.tsx
- host_v2/src/components/Timer.tsx
- host_v2/src/pages/EndGameLobby.tsx
- host_v2/src/pages/InterimLeaderboard.tsx
- host_v2/src/pages/Leaderboard.tsx
- host_v2/src/pages/StartGame.tsx
- play/src/components/ConfidenceMeterCard.tsx
- play/src/components/DiscussAnswerCard.tsx
- play/src/components/NewPointsIndicator.tsx
- play/src/components/ScoreIndicator.tsx
- play/src/pages/GameInProgress.tsx
- play/src/pages/pregame/JoinGame.tsx
Bugs resolved via [this github issue](https://github.com/rightoneducation/righton-app/issues/1197)
> [Host_v2] - QA #3 Bug Resolution

- central_v2/src/App.tsx
- central_v2/src/components/Header.tsx
- central_v2/src/containers/AppContainer.tsx
- central_v2/src/lib/Theme.tsx
- central_v2/src/lib/styledcomponents/HeaderContainerStyledComponent.tsx
- central_v2/src/lib/styledcomponents/SignUpStyledComponents.tsx
- central_v2/src/pages/SignUp.tsx
- central_v2/src/switches/AppSwitch.tsx
Adds `/signup` route and containers
> [Central_v2] - SignUp Prelim

- central_v2/public/locales/en/translation.json
- central_v2/public/locales/es/translation.json
- central_v2/src/components/button/ButtonModels.ts
- central_v2/src/components/cardcarousel/CardCarousel.css
- central_v2/src/components/cardcarousel/CardCarousel.tsx
- central_v2/src/components/cardgallery/CardGallery.tsx
- central_v2/src/components/cards/QuestionCard.tsx
- central_v2/src/components/cards/QuestionCardSkeleton.tsx
- central_v2/src/lib/Theme.tsx
- central_v2/src/lib/styledcomponents/ExploreStyledComponents.tsx
- central_v2/src/pages/ExploreGames.tsx
- central_v2/src/pages/ExploreQuestions.tsx
> [Central_v2] - Design System Updates - Explore Questions

- central_v2/src/components/cardgallery/CardGallery.tsx
- central_v2/src/components/librarytabs/LibraryTabsQuestions.tsx
- central_v2/src/lib/CentralModels.tsx
- central_v2/src/lib/styledcomponents/MyLibraryStyledComponent.tsx
Hey Mike, 
I'll cover this at our upcoming paired programming meeting. Here's the UI components for the Question Bank part of the Create a Game flow:
Note that per Rod's comment, we should remove the Draft tab in this part of the app (so you can take that out for your use case).
> [Central_v2] - Question Bank components for Create a Game

- central_v2/src/lib/helperfunctions/createGame/CreateGameTemplateHelperFunctions.tsx
- central_v2/src/pages/CreateGame.tsx
- networking/src/APIClients/templates/GameQuestionsAPIClient.ts
**Issue:**
Previously, creating a public game question failed due to incorrect type checking during the network response handling. Additionally, image uploads for game templates were not integrated into the creation flow, causing game templates to lack image associations.
*This PR introduces two main updates:*
Game Image Support
- Users can now upload an image or provide an image URL when creating a game. The image is uploaded to S3 and its URL path is saved as part of the game template.
Modification to: GameQuestion Creation
- Previously, game question creation was failing due to designated key for handling with the GraphQL response (key on data object). This PR fixes the dynamic query mapping using the create${type}GameQuestions pattern to ensure the correct mutation is …
> Create Game Question & modify GameQuestionsApiClient

- central_v2/src/hooks/useCentralDataActions.tsx
- networking/src/APIClients/gamesession/index.ts
- networking/src/APIClients/gamesession/interfaces/index.ts
Resolves: https://github.com/rightoneducation/righton-app/issues/1649
The user is now directed to the home page once logged out.
File modified: 
- useCentralDataAction.tsx: Added navigate to handleLogOut function.
> [Central_v2] - Bug Resolution - c11

- central_v2/src/pages/CreateGame.tsx
- networking/amplify/backend/api/mobile/schema.graphql
- networking/src/APIClients/gamesession/index.ts
- networking/src/APIClients/gamesession/interfaces/index.ts
- networking/src/AWSMobileApi.ts
- networking/src/graphql/mutations.js
- networking/src/graphql/mutations.ts
- networking/src/graphql/queries.js
- networking/src/graphql/queries.ts
- networking/src/graphql/subscriptions.js
- networking/src/graphql/subscriptions.ts
Resolves: https://github.com/rightoneducation/righton-app/issues/1650
> [Central_v2] - Bug Resolution - J1

- central_v2/src/components/button/favouritebutton/FavouriteButton.tsx
- central_v2/src/components/cardgallery/CardGallery.tsx
- central_v2/src/components/cards/GameCard.tsx
- central_v2/src/components/cards/QuestionCard.tsx
- central_v2/src/components/librarytabs/LibraryTabs.tsx
- central_v2/src/components/librarytabs/LibraryTabsContent.tsx
- central_v2/src/components/questiontabs/QuestionTabs.tsx
- central_v2/src/components/questiontabs/QuestionTabsSelectedQuestion.tsx
- central_v2/src/hooks/useCentralDataActions.tsx
- central_v2/src/lib/helperfunctions/MyLibraryHelperFunctions.tsx
- central_v2/src/pages/ExploreGames.tsx
- central_v2/src/pages/ExploreQuestions.tsx
- central_v2/src/pages/MyLibrary.tsx
- central_v2/src/pages/ViewGame.tsx
- central_v2/src/switches/AppSwitch.tsx
- networking/src/APIClients/datamanagers/CentralDataManagerAPIClient.ts
- networking/src/APIClients/datamanagers/interfaces/ICentralDataManagerAPIClient.ts
- networking/src/APIClients/templates/GameTemplateAPIClient.ts
- networking/src/APIClients/templates/QuestionTemplateAPIClient.ts
- networking/src/APIClients/user/UserAPIClient.ts
Resolves: https://github.com/rightoneducation/righton-app/issues/1664
> [Central_v2] - Bug Resolution - M10

- central_v2/src/components/cardgallery/CardGallery.tsx
- central_v2/src/components/cards/creategamecard/SelectPhaseButton.tsx
- central_v2/src/components/cards/createquestion/CorrectAnswerCard.tsx
- central_v2/src/lib/styledcomponents/CentralStyledComponents.tsx
- networking/src/APIClients/gamesession/index.ts
- networking/src/APIClients/gamesession/interfaces/index.ts
Resolves [#1657](https://github.com/rightoneducation/righton-app/issues/1657).
> [Central_v2] - Bug Resolution - M7

- central_v2/src/components/profile/OwnerTag.tsx
- central_v2/src/components/questiontabs/QuestionTabs.tsx
- central_v2/src/components/questiontabs/QuestionTabsSelectedQuestion.tsx
- central_v2/src/lib/styledcomponents/QuestionTabsStyledComponents.tsx
Resolves https://github.com/rightoneducation/righton-app/issues/1644.
- `/questions` mobile view is now scrollable with buttons and owner tag containerized with the question card.
> [Central_v2] - Bug Resolution - M2

- central_v2/src/components/button/Button.tsx
- central_v2/src/components/button/ButtonModels.ts
- central_v2/src/lib/styledcomponents/ButtonStyledComponents.tsx
- central_v2/src/pages/CreateQuestion.tsx
Resolves: https://github.com/rightoneducation/righton-app/issues/1653
> [Central_v2] - Bug Resolution - M5

- central_v2/src/components/Header.tsx
- central_v2/src/components/librarytabs/LibraryTabsContent.tsx
- central_v2/src/components/questiontabs/QuestionTabs.tsx
- central_v2/src/components/questiontabs/QuestionTabsContentContainer.tsx
- central_v2/src/components/questiontabs/QuestionTabsSelectedQuestion.tsx
- central_v2/src/hooks/useCentralDataActions.tsx
- central_v2/src/lib/helperfunctions/MyLibraryHelperFunctions.tsx
- central_v2/src/pages/ExploreQuestions.tsx
- central_v2/src/pages/MyLibrary.tsx
Resolution: Full stack implementation including new GSI's and Queries.
**Specific Issue: Navigating question tabs results in blank content being rendered.**
Resolution
> [Central_v2] - Triage Doc - Bug Fixes 2

- website/public/index.html
- website/src/components/article/ArticleCard.tsx
- website/src/components/homepage/OpeningText.tsx
- website/src/components/positive/WannaPlayContainer.tsx
- website/src/lib/styledcomponents/StyledHomePageComponents/StyledHomePageComponents.tsx
- website/src/pages/HowItWorks.tsx
- All updates while Drew was on Vacation.
> Muhammad qureshi  designteamupdate

- central_v2/public/index.html
- host_v2/public/index.html
- networking/src/global.ts
- play/public/index.html
- website/public/index.html
Adds Google Analytics tags to:
- `www.rightoneducation.com`
- `central.rightoneducation.com`
- `host.rightoneducation.com`
- `play.rightoneducation.com`
> Google Analytics
